language: php


dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
    - |
      # php.ini configuration
      INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      phpenv config-rm xdebug.ini || echo "xdebug not available"
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo session.gc_probability = 0 >> $INI
      echo opcache.enable_cli = 1 >> $INI

before_script:
  - composer install --dev

script:
  - bin/atoum

notifications:
  email:
    - ci@verylastroom.com
